# Assignment #1 Tips

This experiment generates two samples, water and beer.  The skeptic says that there is no difference between the two groups.  The classical approach is to do a two sample t-test (we will see that later).  The numerical approach is to shuffle the data many times and calculate how likely is to get a result as extreme or more than the experiment.

We need to shuffle an exisiting sample because we don't have a way to generate data that follows the distribution of water and beer (DGP - Data Generation Process).

We will use numpy library.  One of the reasons NumPy is so important for numerical computations in Python is because it is designed for efficiency on large arrays of data.

In [1]:
import numpy as np

In [2]:
np.random.shuffle?

Docstring:
shuffle(x)
-------

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

Parameters

x : array_like
    The array or list to be shuffled.

### Returns
--------
None

### Examples
--------
 arr = np.arange(10)
 np.random.shuffle(arr)
 arr
[1 7 5 2 9 4 3 6 0 8]

Multi-dimensional arrays are only shuffled along the first axis:

 arr = np.arange(9).reshape((3, 3))
 np.random.shuffle(arr)
 arr
array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])
Type:      builtin_function_or_method

In [6]:
array_1 = np.arange(0,10,1)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(array_1)
array_1

array([5, 1, 0, 9, 4, 2, 3, 7, 6, 8])

Array is a 'in place' function, it changes the original data.

In [9]:
#np.random.shuffle(array)
#array_1

Let's see how shuffle only randomizes along the first axis

In [17]:
array_2 = np.arange(0,50,1).reshape(-1,10)
array_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
np.random.shuffle(array_2)
array_2

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

Rows were shuffled, not the content of each row.

-----

## Some array properties

Elements of an array can be accessed by using the array properties.  Regular Python functions can used to access and perform calculations on the elements of an array.

In [40]:
array_1 = np.arange(0,9,1)
array_1[0]

0

In [68]:
def sum_array(array):
    array_sum = 0
    for i in range(0,len(array)):
        array_sum = array_sum + array[i]
    return array_sum

In [69]:
sum_array(array_1)

36

Arrays can be split.

In [70]:
array_1_part1 = array_1[:3]
array_1_part2 = array_1[3:]

In [71]:
array_1_part1

array([0, 1, 2])

In [72]:
array_1_part2

array([3, 4, 5, 6, 7, 8])

In [73]:
array_split = np.split(array_1,[0,3],axis=0)

In [74]:
array_1_split = array_split[1]

In [75]:
array_1_split

array([0, 1, 2])

In [76]:
array_1_split2 = array_split[2]
array_1_split2

array([3, 4, 5, 6, 7, 8])

Arithmetical operations can be performed on the elements of arrays by using numpy functions

In [77]:
array_1.mean()

4.0